version: '3.4'

services:
  vacinow_front:
    image: vacinow_front
    restart: unless-stopped
    build: ./
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  nginx:
    build: ./nginx
    ports:
      - 80:80
